command_timeout = 5000

format = "[┌─$all](dimmed white) "

[character]
format = "[└─](dimmed white)$symbol"
success_symbol = "[\\$](bold)"

[directory]
format = "\\([$path]($style)[$read_only]($read_only_style)\\) "

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "white"

[gcloud]
symbol = " "
disabled = true

[aws]
symbol = " "
disabled = false
style = "bold white"

[battery]
disabled = true
